### ISSUE TITLE
Error al incluir datos: Field 'apellido_usuario' doesn't have a default value

### ISSUE THREAD

**Issue by aorviz** [csalgadow/demokratian_2.x.x#9]
Hola:

Intentando instalar demokratian con la versión 2.3.6 que ofrece a día de hoy GitHub, en la fase donde se piden los datos personales del adminstrador de la plataforma aparece el siguiente error:

`Se ha producido un error: Error al incluir datos: Field 'apellido_usuario' doesn't have a default value`

He probado a poner un solo apellido y a eliminar la tilde del nombre, pero sigue ofreciendo el mismo error.

Gracia y un saludo.

**Comment by csalgadow** [comment]
Hola
Muchas gracias por reportarnos este bug, intentaremos resolverlo lo antes posible
Podríais decirnos que base de datos y versión estáis usando. Para intentar aislar el problema y reproducirlo en nuestro servidor.

**Comment by aorviz** [comment]
El server es un  Ubuntu 16.04.2 que te instala automáticamente Amazon
cuando despliegas la máquina. La versión de la bbdd es la que viene con los
paquetes estándar de Ubuntu.

aorviz@maquina:~$ mysqld --version
mysqld  Ver 5.7.19-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))
aorviz@maquina:~$


Saludos.

2017-07-31 12:22 GMT+02:00 Carlos Salgado <notifications@github.com>:

**Comment by aorviz** [comment]
El problema estaba en que las opciones por defecto que vienen en el paquete de Ubuntu incluyen la opción global del servidor mysql STRICT_TRANS_TABLES, lo que obliga a definir un valor en cada INSERT o UPDATE o bien fijar uno "default" en la definición. La solución elegante para Ubuntu la podéis encontrar en [este enlace](https://askubuntu.com/questions/811831/whats-the-correct-way-to-revert-mysql-5-7-strict-mode-back-to-how-it-was-in-5-6).

Muchas gracias, ya está todo "up & running" ;-)
